name: ✨ Feature request
description: Suggest a new component or enhancement to existing components
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []
body:
    - type: markdown
      attributes:
          value: |
              Thanks for suggesting a new feature! Please fill out the form below to help us understand your request.

    - type: checkboxes
      id: prerequisites
      attributes:
          label: Prerequisites
          description: Please confirm the following before submitting a feature request
          options:
              - label: I have searched existing issues to ensure this feature hasn't been requested already
                required: true
              - label: I have checked the documentation to confirm this feature doesn't exist
                required: true
              - label: This feature aligns with the project's goals and would benefit the community
                required: false

    - type: dropdown
      id: feature-type
      attributes:
          label: Feature type
          description: What type of feature are you requesting?
          options:
              - New Component
              - Component Enhancement
              - New Component Variant
              - Accessibility Improvement
              - Performance Improvement
              - Developer Experience (DX) Improvement
              - Documentation Improvement
              - Other
      validations:
          required: true

    - type: input
      id: component-name
      attributes:
          label: Component name
          description: If this is about a specific component, which one?
          placeholder: "e.g., Button, Input, Modal, etc."

    - type: textarea
      id: feature-description
      attributes:
          label: Feature description
          description: A clear and concise description of what you want to happen
          placeholder: Describe the feature you'd like to see implemented
      validations:
          required: true

    - type: textarea
      id: problem-statement
      attributes:
          label: Problem statement
          description: What problem does this feature solve? What use case does it address?
          placeholder: |
              Example: "I'm always frustrated when I need to..."
              or "Currently, there's no way to..."
      validations:
          required: true

    - type: textarea
      id: proposed-solution
      attributes:
          label: Proposed solution
          description: Describe the solution you'd like to see implemented
          placeholder: A clear and concise description of what you want to happen

    - type: textarea
      id: api-design
      attributes:
          label: Proposed API design
          description: If applicable, show how you envision the component API
          render: tsx
          placeholder: |
              <NewComponent
                variant="primary"
                size="md"
                onAction={() => {}}
              >
                Content
              </NewComponent>

    - type: textarea
      id: use-cases
      attributes:
          label: Use cases
          description: Describe specific use cases where this feature would be helpful
          placeholder: |
              1. Use case 1: Description
              2. Use case 2: Description
              3. Use case 3: Description

    - type: textarea
      id: alternatives
      attributes:
          label: Alternatives considered
          description: Describe alternatives you've considered or workarounds you're currently using
          placeholder: What alternative solutions or features have you considered?

    - type: textarea
      id: examples
      attributes:
          label: Examples from other libraries
          description: Are there examples of this feature in other UI libraries or design systems?
          placeholder: |
              - Material-UI: [link or description]
              - Ant Design: [link or description]
              - Chakra UI: [link or description]

    - type: dropdown
      id: priority
      attributes:
          label: Priority level
          description: How important is this feature to you?
          options:
              - Low - Nice to have
              - Medium - Would improve my workflow
              - High - Blocking my project
              - Critical - Essential for accessibility or functionality

    - type: checkboxes
      id: requirements
      attributes:
          label: Requirements
          description: What requirements should this feature meet?
          options:
              - label: Must be accessible (WCAG 2.1 AA compliant)
              - label: Must be responsive (mobile-first)
              - label: Must follow existing design patterns
              - label: Must be TypeScript compatible
              - label: Must work with keyboard navigation
              - label: Must work with screen readers
              - label: Must have comprehensive documentation
              - label: Must include Storybook stories

    - type: checkboxes
      id: contribution
      attributes:
          label: Contribution
          description: Are you willing to contribute to this feature?
          options:
              - label: I'm willing to implement this feature
              - label: I'm willing to help with design/specification
              - label: I'm willing to help with testing
              - label: I'm willing to help with documentation

    - type: textarea
      id: design-mockups
      attributes:
          label: Design mockups/references
          description: If you have any design mockups, wireframes, or visual references, please share them
          placeholder: Drag and drop images or paste URLs here

    - type: textarea
      id: additional-context
      attributes:
          label: Additional context
          description: Add any other context, screenshots, or examples about the feature request
          placeholder: Any additional information that might be helpful
